@startuml
package "algorithm" {
    together {
        interface ArcInspector {
            **double** getCost​(Arc);
            **int** getMaximumSpeed();
            **AbstractInputData.Mode** getMode();
            **boolean** isAllowed​(Arc);
        }
        
        ArcInspector ..> AbstractInputData
        class AbstractInputData {
            **AbstractSolution** run();
            **AbstractInputData** getInputData();
        }
    }
    class AbstractSolution {
        **AbstractInputData** getInputData();
        **Duration** getsolvingTime();
        **AbstractSolution.Status** getStatus();
        **boolean** isFeasible();
    }
    note right: AbstractSolution.Status : \nFEASIBLE ; INFEASIBLE ;\nOPTIMAL ; UNKNOWN
    
    AbstractInputData <.. AbstractSolution
    package algorithm.shortestpath {
        interface ShortestPathObserver {
            **void** notifyDestinationReached(Node destination);
            **void** notifyNodeMarked​(Node nodeMarked);
            **void** notifyNodeReached(Node nodeReached);
            **void** notifyOriginProcessed(Node origin);
        }	
        class AStarAlgorithm {
            
        } 
        together { 
            class BellmanFordAlgorithm {
                
            } 
            class DijkstraAlgorithm {
                
            }
            class ShortestPathAlgorithm {
                **ShortestPathData** getInputData()
                **void** notifyDestinationReached​(Node node)
                **void** notifyNodeMarked​(Node node)
                **void** notifyNodeReached​(Node node)
                **void** notifyOriginProcessed​(Node node)
                **ShortestPathSolution** run()
            } 	
        }
        DijkstraAlgorithm <|-- AStarAlgorithm
        DijkstraAlgorithm ..> ShortestPathSolution
        BellmanFordAlgorithm ..> ShortestPathSolution
        ShortestPathAlgorithm "1..*" --> "1" ShortestPathData
        	 
        ShortestPathAlgorithm <|-- BellmanFordAlgorithm
        ShortestPathAlgorithm  <|--  DijkstraAlgorithm
        
        ShortestPathAlgorithm "1" --> "*" ShortestPathObserver
        class ShortestPathData {
            **Node** getDestination()
            **Node** getOrigin() 	 
            **String** toString()
        } 	 
        ShortestPathData --|> AbstractInputData
        ArcInspector <-- ShortestPathData
        class ShortestPathSolution {
            **ShortestPathData** getInputData()
            **Path** getPath()
        } 	 
        ShortestPathSolution --|> AbstractSolution
        ShortestPathSolution "1..*" --> "1" ShortestPathData
        class ShortestPathTextObserver {
            **void** notifyDestinationReached​(Node node) 	
            **void** notifyNodeMarked​(Node node) 	
            **void** notifyNodeReached​(Node node) 	
            **void** notifyOriginProcessed​(Node node) 	
        }
        ShortestPathTextObserver --|> ShortestPathObserver
    }
}
@enduml